# Generated by Django 4.2.27 on 2025-12-03 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
